### ISSUE TITLE
Sort video files

### ISSUE THREAD

**Issue by LewisSpring** [acrojax-open/photos2folders#11]
I'd would be good if video files were sorted as well as images.
This program is brilliant though!

**Comment by borgib** [comment]
I agree with this! It would be SO helpful! Let me tell you why. I use One Drive to back up the photos from mine and my wife's phones. We have young children so we're always taking photos and videos so there are TONS of them. One Drive dumps them all in a Camera Roll folder. Every so often I use this application to sort the files in the camera roll folder. It would be HUGE if that could include video files too!

**Comment by LewisSpring** [comment]
closed - no response
